### ISSUE TITLE
Picture-in-Picture UI Design

### ISSUE THREAD

**Issue by benkenobi007** [meething/webrtc-gun#59]
###  Mockup for picture in picture UI
Currently purely static built using vanilla HTML and CSS.

[Demo on glitch](https://benkenobi007-gun-design.glitch.me/) 

### **TODO:**
- [ ] Add JS logic to enable button functionality. 
- [ ] Integrate into main codebase.
- [ ] Modify design based on feedback.
- [ ] Port to SCSS (if required)

**Comment by QVDev** [comment]
PIP design, just to clarify this. Its not gonna take a whole website space right? Is just a "widget" ui that can be placed on a website? Like in the right bottom of a page?

**Comment by InformationArchitect** [comment]
Yes the size of the div is fixed rn to 560 by 560 px but we werent clear on
whether there is a set technical size limitation or rule for the PIP
browser feature?
